### ISSUE TITLE
No sound in Blender

### ISSUE THREAD

**Issue by kenos1** [edolstra/nix-warez#16]
Sound does not work in Blender VSE. I tried putting in audio strips into the video sequence editor and no sound is playing during playback. GNOME does not pick up Blender playing sound.

**Comment by the-furry-hubofeverything** [comment]
Blender 3.6+ (maybe 3.3+, can't check) uses OpenAL for audio by default, which isn't included in the closure. For a workaround, use SDL under Preferences > System > Sound > Audio Device
