### ISSUE TITLE
blender_4_2 missing

### ISSUE THREAD

**Issue by Skribbles32** [edolstra/nix-warez#24]
I would like to be able to use the latest Blender LTS (4.2) on my NixOS, without any missing features (the Blender in nixpkgs is missing Optix).

I have noticed that this blender flake is missing blender_4_2, but for now I'll have to use blender_4_1 I guess. Disappointing since Blender 4.2 added/changed a lot of things.

**Comment by edolstra** [comment]
Will have a look at adding it.

**Comment by edolstra** [comment]
Fixed in dd4673c825c439bffe306646a008c8de4b95f405.
