### ISSUE TITLE
Expose mkBlender 

### ISSUE THREAD

**Issue by leiserfg** [edolstra/nix-warez#6]
I will like to be able to use mkBlender for building certain  (non stable) blender, like nightly or a custom branch  and `mkBlender` should work fine if I just change the url and hash.

**Comment by edolstra** [comment]
Yeah, we could make it available as a flake output named `lib.mkBlender`. Do you want to make a PR for that?

**Comment by leiserfg** [comment]
I'll try, I'm still a noob in nix.
